<!--
* Dynamic Dreamz
* @category   design
* @package    base_default
* @copyright  Copyright (c) 2014-2015 Dynamic Dreamz. (http://www.dynamicdreamz.com/)
* @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL)
-->

<?php /** @var $this Mage_Sales_Block_Order_Info */ ?>
<?php $_order = $this->getOrder() ?>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<div class="page-title title-buttons">
    <h1><?php echo $this->__('Order #%s - %s', $_order->getRealOrderId(), $_order->getStatusLabel()) ?></h1>
    <?php echo $this->getChildHtml('buttons') ?>
</div>
<?php echo $this->getStatusHistoryRssUrl($_order) ?>
<dl class="order-info">
    <dt><?php echo $this->__('About This Order:') ?></dt>
    <dd>
        <?php $_links = $this->getLinks(); ?>
        <ul id="order-info-tabs">
            <?php foreach ($_links as $_link): ?>
                <?php if ($_link->getUrl()): ?>
                    <li><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
                <?php else: ?>
                    <li class="current"><?php echo $_link->getLabel() ?></li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
        <script type="text/javascript">decorateGeneric($('order-info-tabs').select('LI'), ['first', 'last']);</script>
    </dd>
</dl>
<p class="order-date"><?php echo $this->__('Order Date: %s', $this->formatDate($_order->getCreatedAtStoreDate(), 'long')) ?></p>
<?php if (!$_order->getIsVirtual()): ?>
    <div class="col2-set order-info-box">
        <div class="col-1">
            <div class="box">
                <div class="box-title">
                    <h2><?php echo $this->__('Shipping Address') ?></h2>
                </div>
                <div class="box-content">
                    <address><?php echo $_order->getShippingAddress()->format('html') ?></address>
                </div>
            </div>
        </div>
        <div class="col-2">
            <div class="box">
                <div class="box-title">
                    <h2><?php echo $this->__('Shipping Method') ?></h2>
                </div>
                <div class="box-content">
                    <?php if ($_order->getShippingDescription()): ?>
                        <?php echo $this->escapeHtml($_order->getShippingDescription()) ?>
                    <?php else: ?>
                        <p><?php echo $this->helper('sales')->__('No shipping information available'); ?></p>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
<div class="col2-set order-info-box">
    <div class="col-1">
        <div class="box">
            <div class="box-title">
                <h2><?php echo $this->__('Billing Address') ?></h2>
            </div>
            <div class="box-content">
                <address><?php echo $_order->getBillingAddress()->format('html') ?></address>
            </div>
        </div>
    </div>
    <div class="col-2">
        <div class="box box-payment">
            <div class="box-title">
                <h2><?php echo $this->__('Payment Method') ?></h2>
            </div>
            <div class="box-content">
                <?php echo $this->getPaymentInfoHtml() ?>
            </div>
        </div>
    </div>
</div>
<?php
if (Mage::helper('upload')->isEnabled()) {
    ?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl("css/upload/upload.css") ?>">
    <div class="col1-set order-info-box fileupload box">
        <div class="box-title">
            <h2><?php echo $this->__('Uploaded File Information') ?></h2>
        </div>
        <div class="box-content">
            <div class="cart-fileupload">
                <table class="fileupload-table">
                    <?php
                    try {
                        $collection = Mage::getModel('upload/order')->getFiles($_order);
                        if (count($collection->getData()) > 0) {
                            ?>
                            <tr>
                                <td class="head-label"><strong><label><?php echo Mage::helper('sales')->__('File Type') ?></label></strong></td>
                                <td class="head-label"><strong><label><?php echo Mage::helper('sales')->__('Thumbnail') ?></label></strong></td>
                                <td class="head-label"><strong><label><?php echo Mage::helper('sales')->__('File Name') ?></label></strong></td>
                            </tr>
                            <?php
                            $url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'uploads';
                            $path = Mage::getBaseDir('media') . DS . 'uploads';
                            ?>
                            <?php foreach ($collection as $data): ?>
                            <?php $filepath = str_replace('/', '&', $data['filename']); ?>
                            <?php $file_name = substr($data['filename'], strrpos($data['filename'], '/') + 1); ?>
                                <tr>
                                    <?php //?>
                                    <td class="upload-label"><label><strong><?php echo $data['type'] ?></strong></label></td>
                                    <?php
                                    $_ext = pathinfo($data['filename'], PATHINFO_EXTENSION);
                                    if ($_ext == 'jpeg' || $_ext == 'jpg' || $_ext == 'png' || $_ext == 'ico' || $_ext == 'gif') {
                                        if (file_exists($path . $data['filename'])) {
                                            ?>
                                            <td class="upload-value"><a href="<?php echo $url . $data['filename']; ?>" target="_blank"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'uploads' . $data['filename']; ?>" height="35" width="40"></a></td>
                                        <?php } else { ?>
                                            <td class="upload-value"><a href="<?php echo $url . $data['filename']; ?>" target="_blank"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'uploads' . DS . 'icons/default.png'; ?>" height="40" width="45"></a></td>
                                            <?php
                                        }
                                    } else {
                                        ?>
                                        <td class="upload-value">
                                            <a href="<?php echo $url . $data['filename']; ?>" target="_blank">
                                                <?php if (Mage::helper('upload')->checkFileType($_ext) == 'Unknown') { ?>
                                                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'uploads' . DS . 'icons/unknown.png'; ?>" height="40" width="45">
                                                <?php } else if (!file_exists($path . $data['filename'])) { ?>
                                                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'uploads' . DS . 'icons/missing.png'; ?>" height="40" width="45">
                                                <?php } else { ?>
                                                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'uploads' . DS . 'icons/' . $_ext . '.png'; ?>" height="40" width="45">
                                                <?php } ?>
                                            </a>
                                        </td>
                                    <?php } ?>
                                    <?php if (file_exists($path . $data['filename'])) { ?>
                                        <td class="upload-value"><a href="<?php echo $url . $data['filename']; ?>" target="_blank"><?php echo $file_name; ?></a></td>
                                    <?php } else { ?>
                                        <td class="upload-value">
                                            <a href="#"><?php echo $file_name; ?></a>
                                            <label><strong><i><?php echo $this->__('  ( File no longer exists )'); ?></i></strong></label>
                                        </td>

                                    <?php } ?>
                                </tr>
                            <?php endforeach; ?>
                        <?php } else { ?>
                            <tr>
                                <td class="upload-value"><?php echo $this->__('There is no file uploaded for this order') ?></td>
                            </tr>
                            <?php
                        }
                    } catch (Exception $e) {
                        Mage::log($e->getMessage());
                    }
                    ?>
                </table>
            </div>
        </div>
    </div>
<?php } ?>
